services:

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-task_manager_api_rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-task_manager_api}
      MYSQL_USER: ${MYSQL_USER:-task_manager_api_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-task_manager_api_password}
    ports:
      - "3313:3306"  
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - task_manager_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: ${PMA_HOST:-mysql}
      PMA_USER: ${PMA_USER:-task_manager_api_user}
      PMA_PASSWORD: ${PMA_PASSWORD:-task_manager_api_password}
    ports: 
      - "8080:80"
    depends_on:
      - mysql
    networks: 
      - task_manager_network

volumes:
  mysql_data:

networks:
  task_manager_network:
